// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rolucmepkgdzwogntxdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvbHVjbWVwa2dkendvZ250eGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NDE1MTUsImV4cCI6MjA2MjQxNzUxNX0.pjsEz15lFqeLOERrdEHBdy4VOY6j7EGk1sILXylslvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);